// Package apimanagerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package apimanagerevents

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	"github.com/pershin-daniil/ninja-chat-bank/internal/types"
)

// Defines values for EventType.
const (
	EventTypeChatClosedEvent EventType = "ChatClosedEvent"
	EventTypeNewChatEvent    EventType = "NewChatEvent"
	EventTypeNewMessageEvent EventType = "NewMessageEvent"
)

// ChatClosedEvent defines model for ChatClosedEvent.
type ChatClosedEvent struct {
	CanTakeMoreProblems bool      `json:"canTakeMoreProblems"`
	ChatID              ChatID    `json:"chatId"`
	ID                  ID        `json:"eventId"`
	EventType           string    `json:"eventType"`
	RequestID           RequestID `json:"requestId"`
}

// ChatID defines model for ChatID.
type ChatID = types.ChatID

// ClientID defines model for ClientID.
type ClientID = types.UserID

// Event defines model for Event.
type Event struct {
	union json.RawMessage
}

// ID defines model for EventID.
type ID = types.EventID

// EventType defines model for EventType.
type EventType string

// MessageID defines model for MessageID.
type MessageID = types.MessageID

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	CanTakeMoreProblems bool      `json:"canTakeMoreProblems"`
	ChatID              ChatID    `json:"chatId"`
	ClientID            ClientID  `json:"clientId"`
	ID                  ID        `json:"eventId"`
	EventType           string    `json:"eventType"`
	RequestID           RequestID `json:"requestId"`
}

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	ClientID  ClientID  `json:"authorId"`
	Body      string    `json:"body"`
	ChatID    ChatID    `json:"chatId"`
	CreatedAt time.Time `json:"createdAt"`
	ID        ID        `json:"eventId"`
	EventType string    `json:"eventType"`
	MessageID MessageID `json:"messageId"`
	RequestID RequestID `json:"requestId"`
}

// RequestID defines model for RequestID.
type RequestID = types.RequestID

// AsNewChatEvent returns the union data inside the Event as a NewChatEvent
func (t Event) AsNewChatEvent() (NewChatEvent, error) {
	var body NewChatEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewChatEvent overwrites any union data inside the Event as the provided NewChatEvent
func (t *Event) FromNewChatEvent(v NewChatEvent) error {
	v.EventType = "NewChatEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewChatEvent performs a merge with any union data inside the Event, using the provided NewChatEvent
func (t *Event) MergeNewChatEvent(v NewChatEvent) error {
	v.EventType = "NewChatEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatClosedEvent returns the union data inside the Event as a ChatClosedEvent
func (t Event) AsChatClosedEvent() (ChatClosedEvent, error) {
	var body ChatClosedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatClosedEvent overwrites any union data inside the Event as the provided ChatClosedEvent
func (t *Event) FromChatClosedEvent(v ChatClosedEvent) error {
	v.EventType = "ChatClosedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatClosedEvent performs a merge with any union data inside the Event, using the provided ChatClosedEvent
func (t *Event) MergeChatClosedEvent(v ChatClosedEvent) error {
	v.EventType = "ChatClosedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNewMessageEvent returns the union data inside the Event as a NewMessageEvent
func (t Event) AsNewMessageEvent() (NewMessageEvent, error) {
	var body NewMessageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewMessageEvent overwrites any union data inside the Event as the provided NewMessageEvent
func (t *Event) FromNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewMessageEvent performs a merge with any union data inside the Event, using the provided NewMessageEvent
func (t *Event) MergeNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"eventType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ChatClosedEvent":
		return t.AsChatClosedEvent()
	case "NewChatEvent":
		return t.AsNewChatEvent()
	case "NewMessageEvent":
		return t.AsNewMessageEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
