// Code generated by cmd/gen-types; DO NOT EDIT.
package types

import (
	"database/sql/driver"
	"errors"

	"github.com/google/uuid"
)

var ChatIDNil = ChatID(uuid.Nil)

type ChatID uuid.UUID

func NewChatID() ChatID                           { return ChatID(uuid.New()) }
func (t ChatID) String() string                   { return uuid.UUID(t).String() }
func (t ChatID) Value() (driver.Value, error)     { return t.String(), nil }
func (t *ChatID) Scan(src any) error              { return (*uuid.UUID)(t).Scan(src) }
func (t ChatID) MarshalText() ([]byte, error)     { return uuid.UUID(t).MarshalText() }
func (t *ChatID) UnmarshalText(data []byte) error { return (*uuid.UUID)(t).UnmarshalText(data) }
func (t ChatID) IsZero() bool                     { return t == ChatIDNil }
func (t ChatID) Matches(x any) bool {
	v, ok := x.(ChatID)
	if !ok {
		return false
	}
	return t.String() == v.String()
}
func (t ChatID) Validate() error {
	if t.IsZero() {
		return errors.New("zero ChatID")
	}
	return nil
}

var MessageIDNil = MessageID(uuid.Nil)

type MessageID uuid.UUID

func NewMessageID() MessageID                        { return MessageID(uuid.New()) }
func (t MessageID) String() string                   { return uuid.UUID(t).String() }
func (t MessageID) Value() (driver.Value, error)     { return t.String(), nil }
func (t *MessageID) Scan(src any) error              { return (*uuid.UUID)(t).Scan(src) }
func (t MessageID) MarshalText() ([]byte, error)     { return uuid.UUID(t).MarshalText() }
func (t *MessageID) UnmarshalText(data []byte) error { return (*uuid.UUID)(t).UnmarshalText(data) }
func (t MessageID) IsZero() bool                     { return t == MessageIDNil }
func (t MessageID) Matches(x any) bool {
	v, ok := x.(MessageID)
	if !ok {
		return false
	}
	return t.String() == v.String()
}
func (t MessageID) Validate() error {
	if t.IsZero() {
		return errors.New("zero MessageID")
	}
	return nil
}

var ProblemIDNil = ProblemID(uuid.Nil)

type ProblemID uuid.UUID

func NewProblemID() ProblemID                        { return ProblemID(uuid.New()) }
func (t ProblemID) String() string                   { return uuid.UUID(t).String() }
func (t ProblemID) Value() (driver.Value, error)     { return t.String(), nil }
func (t *ProblemID) Scan(src any) error              { return (*uuid.UUID)(t).Scan(src) }
func (t ProblemID) MarshalText() ([]byte, error)     { return uuid.UUID(t).MarshalText() }
func (t *ProblemID) UnmarshalText(data []byte) error { return (*uuid.UUID)(t).UnmarshalText(data) }
func (t ProblemID) IsZero() bool                     { return t == ProblemIDNil }
func (t ProblemID) Matches(x any) bool {
	v, ok := x.(ProblemID)
	if !ok {
		return false
	}
	return t.String() == v.String()
}
func (t ProblemID) Validate() error {
	if t.IsZero() {
		return errors.New("zero ProblemID")
	}
	return nil
}

var RequestIDNil = RequestID(uuid.Nil)

type RequestID uuid.UUID

func NewRequestID() RequestID                        { return RequestID(uuid.New()) }
func (t RequestID) String() string                   { return uuid.UUID(t).String() }
func (t RequestID) Value() (driver.Value, error)     { return t.String(), nil }
func (t *RequestID) Scan(src any) error              { return (*uuid.UUID)(t).Scan(src) }
func (t RequestID) MarshalText() ([]byte, error)     { return uuid.UUID(t).MarshalText() }
func (t *RequestID) UnmarshalText(data []byte) error { return (*uuid.UUID)(t).UnmarshalText(data) }
func (t RequestID) IsZero() bool                     { return t == RequestIDNil }
func (t RequestID) Matches(x any) bool {
	v, ok := x.(RequestID)
	if !ok {
		return false
	}
	return t.String() == v.String()
}
func (t RequestID) Validate() error {
	if t.IsZero() {
		return errors.New("zero RequestID")
	}
	return nil
}

var UserIDNil = UserID(uuid.Nil)

type UserID uuid.UUID

func NewUserID() UserID                           { return UserID(uuid.New()) }
func (t UserID) String() string                   { return uuid.UUID(t).String() }
func (t UserID) Value() (driver.Value, error)     { return t.String(), nil }
func (t *UserID) Scan(src any) error              { return (*uuid.UUID)(t).Scan(src) }
func (t UserID) MarshalText() ([]byte, error)     { return uuid.UUID(t).MarshalText() }
func (t *UserID) UnmarshalText(data []byte) error { return (*uuid.UUID)(t).UnmarshalText(data) }
func (t UserID) IsZero() bool                     { return t == UserIDNil }
func (t UserID) Matches(x any) bool {
	v, ok := x.(UserID)
	if !ok {
		return false
	}
	return t.String() == v.String()
}
func (t UserID) Validate() error {
	if t.IsZero() {
		return errors.New("zero UserID")
	}
	return nil
}

type TypeSet = interface {
	ChatID | MessageID | ProblemID | RequestID | UserID
}

func Parse[T TypeSet](s string) (T, error) {
	v, err := uuid.Parse(s)
	return T(v), err
}

func MustParse[T TypeSet](s string) T {
	return T(uuid.MustParse(s))
}
