// Code generated by options-gen. DO NOT EDIT.
package managerv1

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	canReceiveProblemsUseCase canReceiveProblemsUseCase,
	freeHandsSignal freeHandsSignalUseCase,
	getChatsUC getChatsUseCase,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.canReceiveProblemsUseCase = canReceiveProblemsUseCase
	o.freeHandsSignal = freeHandsSignal
	o.getChatsUC = getChatsUC

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("canReceiveProblemsUseCase", _validate_Options_canReceiveProblemsUseCase(o)))
	errs.Add(errors461e464ebed9.NewValidationError("freeHandsSignal", _validate_Options_freeHandsSignal(o)))
	errs.Add(errors461e464ebed9.NewValidationError("getChatsUC", _validate_Options_getChatsUC(o)))
	return errs.AsError()
}

func _validate_Options_canReceiveProblemsUseCase(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.canReceiveProblemsUseCase, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `canReceiveProblemsUseCase` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_freeHandsSignal(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.freeHandsSignal, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `freeHandsSignal` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_getChatsUC(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.getChatsUC, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `getChatsUC` did not pass the test: %w", err)
	}
	return nil
}
