// Code generated by options-gen. DO NOT EDIT.
package freehands

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	mngPool managerPool,
	mngLoad managerLoadService,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.mngPool = mngPool
	o.mngLoad = mngLoad

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("mngPool", _validate_Options_mngPool(o)))
	errs.Add(errors461e464ebed9.NewValidationError("mngLoad", _validate_Options_mngLoad(o)))
	return errs.AsError()
}

func _validate_Options_mngPool(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.mngPool, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `mngPool` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_mngLoad(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.mngLoad, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `mngLoad` did not pass the test: %w", err)
	}
	return nil
}
