# https://taskfile.dev
version: '3'

silent: true

vars:
  GO_MODULE: github.com/pershin-daniil/ninja-chat-bank
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: v1.56.2
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/.cache"

  TOOLS_DIR:
    sh: echo "`pwd`/bin/tools"
  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.13.1
    mvdan.cc/gofumpt@v0.6.0

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - gofumpt -w {{.GO_FILES}}
    - gci write {{.GO_FILES}} --custom-order -s standard -s default -s "prefix({{.GO_MODULE}})"

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: { CLI_ARGS: "run -v --fix --timeout=5m ./..." }

  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -race ./...

  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/chat-service

  dev-tools:install:
    dir: "{{.TOOLS_DIR}}"
    cmds:
      - echo "- Install dev tools"
      - |
        export GOBIN="{{.TOOLS_DIR}}"
        {{range $i, $tool := .DEV_TOOLS | trim | splitLines}}
        go install {{$tool}}
        {{end}}
      - ls -l "{{.TOOLS_DIR}}"
