# https://taskfile.dev
version: '3'

silent: true

vars:
  GO_MODULE: github.com/pershin-daniil/ninja-chat-bank
  GO_FILES:
    sh: find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./internal/store/*" -not -path "*.gen.go" | tr "\n" " "

  GOLANGCI_LINT_VERSION: v1.56.2
  GOLANGCI_LINT_CACHE:
    sh: echo "$HOME/.cache"

  TOOLS_DIR:
    sh: echo "`pwd`/bin/tools"

  DEV_TOOLS: |
    entgo.io/ent/cmd/ent@v0.13.1
    github.com/daixiang0/gci@v0.13.1
    github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.1.0
    github.com/kazhuravlev/options-gen/cmd/options-gen@v0.32.0
    github.com/onsi/ginkgo/v2/ginkgo@v2.17.1
    go.uber.org/mock/mockgen@v0.4.0
    mvdan.cc/gofumpt@v0.6.0


  DOCKER_COMPOSE_PATHS: |
    ./deploy/local/docker-compose.yml
    ./deploy/local/docker-compose.sentry.yml
    ./deploy/local/docker-compose.swagger-ui.yml

  DOCKER_COMPOSE_CMD: docker compose -f {{ .DOCKER_COMPOSE_PATHS | trim | splitLines | join " -f " }}

  TYPES: |
    ChatID
    FailedJobID
    JobID
    MessageID
    ProblemID
    RequestID
    UserID
  TYPES_PKG: types
  TYPES_DST: ./internal/types/types.gen.go

  ENT_SCHEMA: ./internal/store/schema
  ENT_DIR: ./internal/store/ent-gen

  KEYCLOAK_REALM_PATH: ./deploy/local/ban-realm.json

  CLIENT_V1_PKG: clientv1
  CLIENT_V1_SRC: ./api/client.v1.swagger.yml
  CLIENT_V1_DST: ./internal/server-client/v1/server.gen.go

  ### E2E tests ###
  E2E_CLIENT_V1_DST: ./tests/e2e/api/client/v1/client.gen.go
  E2E_CLIENT_V1_PKG: apiclientv1
  ###


tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: tests
      - task: build

  tidy:
    - echo "- Tidy"
    - go mod tidy
    - task: vendor

  vendor:
    - echo "- Vendor"
    - go mod vendor

  fmt:
    - echo "- Format"
    - |
      export PATH="${PATH}:{{.TOOLS_DIR}}"
      gofumpt -w {{.GO_FILES}}
      gci write {{.GO_FILES}} --custom-order -s standard -s default -s "Prefix({{.GO_MODULE}})" 2> /dev/null

  lint:
    cmds:
      - echo "- Lint"
      - mkdir -p {{.GOLANGCI_LINT_CACHE}}
      - task: lint:cmd
        vars: { CLI_ARGS: "run -v --fix --timeout=5m ./..." }

  lint:cmd:
    cmds:
      - |
        docker run --rm \
          -v "$(pwd):/app" -w /app \
          -v "{{.GOLANGCI_LINT_CACHE}}:/root/.cache" \
          golangci/golangci-lint:{{.GOLANGCI_LINT_VERSION}} \
          golangci-lint {{.CLI_ARGS}}

  tests:
    cmds:
      - echo "- Tests"
      - go test -race ./...

  tests:integration:
    env:
      TEST_LOG_LEVEL: info
      TEST_KEYCLOAK_REALM: Bank
      TEST_KEYCLOAK_CLIENT_ID: integration-testing
      TEST_KEYCLOAK_CLIENT_SECRET: biq7WcbKHgVaalqZDlhqINEi1yGK6aOw
      TEST_KEYCLOAK_TEST_USER: integration_testing
      TEST_KEYCLOAK_TEST_PASSWORD: integration_testing
      PSQL_PASSWORD: chat-service
      PSQL_USER: chat-service
      TEST_PSQL_DEBUG: true
    cmds:
      - echo "- Integration tests"
      - go test -tags integration -count 1 -race ./...

  kc:export:
    cmds:
      - echo "- Exporting realm"
      - "{{.DOCKER_COMPOSE_CMD}} exec keycloak /opt/keycloak/bin/kc.sh export \
          --realm Bank \
          --file /dev/stdout > ./deploy/local/keycloak-bank-realm.json"

  tests:e2e:
    env:
      E2E_CLIENT_V1_API_ENDPOINT: http://localhost:8080/v1

      E2E_KEYCLOAK_BASE_PATH: http://localhost:3010
      E2E_KEYCLOAK_REALM: Bank
      E2E_KEYCLOAK_CLIENT_ID: e2e-testing
      E2E_KEYCLOAK_CLIENT_SECRET: hD3CVXnQ1k3TTUmUA5eHeARIfTQFxM2U
      E2E_KEYCLOAK_CLIENT_DEBUG: false
      E2E_KEYCLOAK_CLIENTS: biba,boba
    dir: "{{.TOOLS_DIR}}"
    cmds:
      - echo "- End-to-end tests..."
      # NOTE: It's important to run tests serial (without `-p` flag) – for correct `clientsPool` sharing.
      - ./ginkgo --fail-fast --timeout=1m --tags e2e {{.CLI_ARGS}} ../../tests/e2e

  build:
    cmds:
      - echo "- Build"
      - go build ./cmd/chat-service

  dev-tools:install:
    dir: "{{.TOOLS_DIR}}"
    cmds:
      - echo "- Install dev tools"
      - |
        export GOBIN="{{.TOOLS_DIR}}"
        {{range $i, $tool := .DEV_TOOLS | trim | splitLines -}}
          go install {{$tool}}
        {{end}}
      - ls -l "{{.TOOLS_DIR}}"

  generate:
    - echo "- Run go generate..."
    - export PATH="${PATH}:{{.TOOLS_DIR}}" && go generate ./...
    - task: gen:types
    - task: ent:gen
    - task: gen:api
    - task: gen:e2e

  gen:types:
    cmds:
      - echo "- Generate types..."
      - go run ./cmd/gen-types {{.TYPES_PKG}} {{ .TYPES | trim | splitLines | join "," }} {{.TYPES_DST}}

  ent:new:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent new --target {{.ENT_SCHEMA}} {{$.CLI_ARGS}}
      - task: tidy

  ent:gen:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/upsert,sql/lock --template ./internal/store/templates/ {{.ENT_SCHEMA}}
      - task: tidy

  gen:api:
    dir: "{{.TOOLS_DIR}}"
    cmds:
      - ./oapi-codegen -old-config-style -package {{.CLIENT_V1_PKG }} ../../{{.CLIENT_V1_SRC}} > ../../{{.CLIENT_V1_DST}}

  gen:e2e:
    dir: "{{.TOOLS_DIR}}"
    cmds:
      - echo "[E2E] Generate client API..."
      - ./oapi-codegen --old-config-style -generate types,client -package {{.E2E_CLIENT_V1_PKG}} ../../{{.CLIENT_V1_SRC}} > ../../{{.E2E_CLIENT_V1_DST}}

  deps:
    cmds:
      - echo "- Run deps containers"
      - "{{.DOCKER_COMPOSE_CMD}} up -d"

  deps:cmd:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} {{.CLI_ARGS}}"

  deps:status:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} ps"

  deps:logs:
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} logs {{.CLI_ARGS}}"

  deps:stop:
    cmds:
      - echo "- Stop deps containers"
      - "{{.DOCKER_COMPOSE_CMD}} stop"

  deps:reset-psql:
    cmds:
      - task: deps:reset
        vars:
          SERVICE: postgres

  deps:reset-sentry:
    cmds:
      - task: deps:reset
        vars:
          SERVICE: sentry sentry-worker cron redis

  deps:reset:
    internal: true
    cmds:
      - "{{.DOCKER_COMPOSE_CMD}} rm -fsv {{.SERVICE}}"
      - "{{.DOCKER_COMPOSE_CMD}} up -d {{.SERVICE}}"
