// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/usecase_mock.gen.go -typed -package=closechatsmocks
//

// Package closechatsmocks is a generated GoMock package.
package closechatsmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	messagesrepo "github.com/pershin-daniil/ninja-chat-bank/internal/repositories/messages"
	problemsrepo "github.com/pershin-daniil/ninja-chat-bank/internal/repositories/problems"
	types "github.com/pershin-daniil/ninja-chat-bank/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockproblemsRepository is a mock of problemsRepository interface.
type MockproblemsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockproblemsRepositoryMockRecorder
}

// MockproblemsRepositoryMockRecorder is the mock recorder for MockproblemsRepository.
type MockproblemsRepositoryMockRecorder struct {
	mock *MockproblemsRepository
}

// NewMockproblemsRepository creates a new mock instance.
func NewMockproblemsRepository(ctrl *gomock.Controller) *MockproblemsRepository {
	mock := &MockproblemsRepository{ctrl: ctrl}
	mock.recorder = &MockproblemsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproblemsRepository) EXPECT() *MockproblemsRepositoryMockRecorder {
	return m.recorder
}

// ResolveAssignedProblem mocks base method.
func (m *MockproblemsRepository) ResolveAssignedProblem(ctx context.Context, chatID types.ChatID, managerID types.UserID) (*problemsrepo.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAssignedProblem", ctx, chatID, managerID)
	ret0, _ := ret[0].(*problemsrepo.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAssignedProblem indicates an expected call of ResolveAssignedProblem.
func (mr *MockproblemsRepositoryMockRecorder) ResolveAssignedProblem(ctx, chatID, managerID any) *MockproblemsRepositoryResolveAssignedProblemCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAssignedProblem", reflect.TypeOf((*MockproblemsRepository)(nil).ResolveAssignedProblem), ctx, chatID, managerID)
	return &MockproblemsRepositoryResolveAssignedProblemCall{Call: call}
}

// MockproblemsRepositoryResolveAssignedProblemCall wrap *gomock.Call
type MockproblemsRepositoryResolveAssignedProblemCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockproblemsRepositoryResolveAssignedProblemCall) Return(arg0 *problemsrepo.Problem, arg1 error) *MockproblemsRepositoryResolveAssignedProblemCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockproblemsRepositoryResolveAssignedProblemCall) Do(f func(context.Context, types.ChatID, types.UserID) (*problemsrepo.Problem, error)) *MockproblemsRepositoryResolveAssignedProblemCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockproblemsRepositoryResolveAssignedProblemCall) DoAndReturn(f func(context.Context, types.ChatID, types.UserID) (*problemsrepo.Problem, error)) *MockproblemsRepositoryResolveAssignedProblemCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockmessagesRepository is a mock of messagesRepository interface.
type MockmessagesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockmessagesRepositoryMockRecorder
}

// MockmessagesRepositoryMockRecorder is the mock recorder for MockmessagesRepository.
type MockmessagesRepositoryMockRecorder struct {
	mock *MockmessagesRepository
}

// NewMockmessagesRepository creates a new mock instance.
func NewMockmessagesRepository(ctrl *gomock.Controller) *MockmessagesRepository {
	mock := &MockmessagesRepository{ctrl: ctrl}
	mock.recorder = &MockmessagesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmessagesRepository) EXPECT() *MockmessagesRepositoryMockRecorder {
	return m.recorder
}

// CreateServiceClientVisible mocks base method.
func (m *MockmessagesRepository) CreateServiceClientVisible(ctx context.Context, reqID types.RequestID, problemID types.ProblemID, chatID types.ChatID, msgBody string) (*messagesrepo.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateServiceClientVisible", ctx, reqID, problemID, chatID, msgBody)
	ret0, _ := ret[0].(*messagesrepo.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateServiceClientVisible indicates an expected call of CreateServiceClientVisible.
func (mr *MockmessagesRepositoryMockRecorder) CreateServiceClientVisible(ctx, reqID, problemID, chatID, msgBody any) *MockmessagesRepositoryCreateServiceClientVisibleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateServiceClientVisible", reflect.TypeOf((*MockmessagesRepository)(nil).CreateServiceClientVisible), ctx, reqID, problemID, chatID, msgBody)
	return &MockmessagesRepositoryCreateServiceClientVisibleCall{Call: call}
}

// MockmessagesRepositoryCreateServiceClientVisibleCall wrap *gomock.Call
type MockmessagesRepositoryCreateServiceClientVisibleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockmessagesRepositoryCreateServiceClientVisibleCall) Return(arg0 *messagesrepo.Message, arg1 error) *MockmessagesRepositoryCreateServiceClientVisibleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockmessagesRepositoryCreateServiceClientVisibleCall) Do(f func(context.Context, types.RequestID, types.ProblemID, types.ChatID, string) (*messagesrepo.Message, error)) *MockmessagesRepositoryCreateServiceClientVisibleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockmessagesRepositoryCreateServiceClientVisibleCall) DoAndReturn(f func(context.Context, types.RequestID, types.ProblemID, types.ChatID, string) (*messagesrepo.Message, error)) *MockmessagesRepositoryCreateServiceClientVisibleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockchatsRepository is a mock of chatsRepository interface.
type MockchatsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockchatsRepositoryMockRecorder
}

// MockchatsRepositoryMockRecorder is the mock recorder for MockchatsRepository.
type MockchatsRepositoryMockRecorder struct {
	mock *MockchatsRepository
}

// NewMockchatsRepository creates a new mock instance.
func NewMockchatsRepository(ctrl *gomock.Controller) *MockchatsRepository {
	mock := &MockchatsRepository{ctrl: ctrl}
	mock.recorder = &MockchatsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatsRepository) EXPECT() *MockchatsRepositoryMockRecorder {
	return m.recorder
}

// GetClientIDByChatID mocks base method.
func (m *MockchatsRepository) GetClientIDByChatID(ctx context.Context, chatID types.ChatID) (types.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientIDByChatID", ctx, chatID)
	ret0, _ := ret[0].(types.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientIDByChatID indicates an expected call of GetClientIDByChatID.
func (mr *MockchatsRepositoryMockRecorder) GetClientIDByChatID(ctx, chatID any) *MockchatsRepositoryGetClientIDByChatIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientIDByChatID", reflect.TypeOf((*MockchatsRepository)(nil).GetClientIDByChatID), ctx, chatID)
	return &MockchatsRepositoryGetClientIDByChatIDCall{Call: call}
}

// MockchatsRepositoryGetClientIDByChatIDCall wrap *gomock.Call
type MockchatsRepositoryGetClientIDByChatIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockchatsRepositoryGetClientIDByChatIDCall) Return(arg0 types.UserID, arg1 error) *MockchatsRepositoryGetClientIDByChatIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockchatsRepositoryGetClientIDByChatIDCall) Do(f func(context.Context, types.ChatID) (types.UserID, error)) *MockchatsRepositoryGetClientIDByChatIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockchatsRepositoryGetClientIDByChatIDCall) DoAndReturn(f func(context.Context, types.ChatID) (types.UserID, error)) *MockchatsRepositoryGetClientIDByChatIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockoutboxService is a mock of outboxService interface.
type MockoutboxService struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxServiceMockRecorder
}

// MockoutboxServiceMockRecorder is the mock recorder for MockoutboxService.
type MockoutboxServiceMockRecorder struct {
	mock *MockoutboxService
}

// NewMockoutboxService creates a new mock instance.
func NewMockoutboxService(ctrl *gomock.Controller) *MockoutboxService {
	mock := &MockoutboxService{ctrl: ctrl}
	mock.recorder = &MockoutboxServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxService) EXPECT() *MockoutboxServiceMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockoutboxService) Put(ctx context.Context, name, payload string, availableAt time.Time) (types.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(types.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockoutboxServiceMockRecorder) Put(ctx, name, payload, availableAt any) *MockoutboxServicePutCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockoutboxService)(nil).Put), ctx, name, payload, availableAt)
	return &MockoutboxServicePutCall{Call: call}
}

// MockoutboxServicePutCall wrap *gomock.Call
type MockoutboxServicePutCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockoutboxServicePutCall) Return(arg0 types.JobID, arg1 error) *MockoutboxServicePutCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockoutboxServicePutCall) Do(f func(context.Context, string, string, time.Time) (types.JobID, error)) *MockoutboxServicePutCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockoutboxServicePutCall) DoAndReturn(f func(context.Context, string, string, time.Time) (types.JobID, error)) *MockoutboxServicePutCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Mocktransactor is a mock of transactor interface.
type Mocktransactor struct {
	ctrl     *gomock.Controller
	recorder *MocktransactorMockRecorder
}

// MocktransactorMockRecorder is the mock recorder for Mocktransactor.
type MocktransactorMockRecorder struct {
	mock *Mocktransactor
}

// NewMocktransactor creates a new mock instance.
func NewMocktransactor(ctrl *gomock.Controller) *Mocktransactor {
	mock := &Mocktransactor{ctrl: ctrl}
	mock.recorder = &MocktransactorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocktransactor) EXPECT() *MocktransactorMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *Mocktransactor) RunInTx(ctx context.Context, f func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MocktransactorMockRecorder) RunInTx(ctx, f any) *MocktransactorRunInTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*Mocktransactor)(nil).RunInTx), ctx, f)
	return &MocktransactorRunInTxCall{Call: call}
}

// MocktransactorRunInTxCall wrap *gomock.Call
type MocktransactorRunInTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MocktransactorRunInTxCall) Return(arg0 error) *MocktransactorRunInTxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MocktransactorRunInTxCall) Do(f func(context.Context, func(context.Context) error) error) *MocktransactorRunInTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MocktransactorRunInTxCall) DoAndReturn(f func(context.Context, func(context.Context) error) error) *MocktransactorRunInTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
