// Code generated by options-gen. DO NOT EDIT.
package sendclientmessagejob

type OptOptionsSetter func(o *Options)

func NewOptions(
	messageProducer messageProducer,
	messageRepository messageRepository,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.messageProducer = messageProducer
	o.messageRepository = messageRepository

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	return nil
}
