// Code generated by options-gen. DO NOT EDIT.
package sendmessage

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	messagesRepository messagesRepository,
	outboxService outboxService,
	problemsRepository problemsRepository,
	transactor transactor,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.messagesRepository = messagesRepository
	o.outboxService = outboxService
	o.problemsRepository = problemsRepository
	o.transactor = transactor

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("messagesRepository", _validate_Options_messagesRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("outboxService", _validate_Options_outboxService(o)))
	errs.Add(errors461e464ebed9.NewValidationError("problemsRepository", _validate_Options_problemsRepository(o)))
	errs.Add(errors461e464ebed9.NewValidationError("transactor", _validate_Options_transactor(o)))
	return errs.AsError()
}

func _validate_Options_messagesRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.messagesRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `messagesRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_outboxService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.outboxService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `outboxService` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_problemsRepository(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.problemsRepository, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `problemsRepository` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_transactor(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.transactor, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `transactor` did not pass the test: %w", err)
	}
	return nil
}
