// Code generated by options-gen. DO NOT EDIT.
package serverdebug

import (
	fmt461e464ebed9 "fmt"

	"github.com/getkin/kin-openapi/openapi3"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	addr string,
	v1ClientSwagger *openapi3.T,
	v1ManagerSwagger *openapi3.T,
	eventsSwagger *openapi3.T,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.addr = addr
	o.v1ClientSwagger = v1ClientSwagger
	o.v1ManagerSwagger = v1ManagerSwagger
	o.eventsSwagger = eventsSwagger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("addr", _validate_Options_addr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("v1ClientSwagger", _validate_Options_v1ClientSwagger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("v1ManagerSwagger", _validate_Options_v1ManagerSwagger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("eventsSwagger", _validate_Options_eventsSwagger(o)))
	return errs.AsError()
}

func _validate_Options_addr(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.addr, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `addr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_v1ClientSwagger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.v1ClientSwagger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `v1ClientSwagger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_v1ManagerSwagger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.v1ManagerSwagger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `v1ManagerSwagger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_eventsSwagger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventsSwagger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventsSwagger` did not pass the test: %w", err)
	}
	return nil
}
