// Package managerevents provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package managerevents

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	"github.com/pershin-daniil/ninja-chat-bank/internal/types"
)

// Defines values for EventType.
const (
	EventTypeChatClosedEvent EventType = "ChatClosedEvent"
	EventTypeNewChatEvent    EventType = "NewChatEvent"
	EventTypeNewMessageEvent EventType = "NewMessageEvent"
)

// ChatClosedEvent defines model for ChatClosedEvent.
type ChatClosedEvent struct {
	CanTakeMoreProblems bool      `json:"canTakeMoreProblems"`
	ChatID              ChatID    `json:"chatId"`
	ID                  ID        `json:"eventId"`
	EventType           string    `json:"eventType"`
	RequestID           RequestID `json:"requestId"`
}

// ChatID defines model for ChatID.
type ChatID = types.ChatID

// ClientID defines model for ClientID.
type ClientID = types.UserID

// Event defines model for Event.
type Event struct {
	union json.RawMessage
}

// ID defines model for EventID.
type ID = types.EventID

// EventType defines model for EventType.
type EventType string

// MessageID defines model for MessageID.
type MessageID = types.MessageID

// NewChatEvent defines model for NewChatEvent.
type NewChatEvent struct {
	CanTakeMoreProblems bool      `json:"canTakeMoreProblems"`
	ChatID              ChatID    `json:"chatId"`
	ClientID            ClientID  `json:"clientId"`
	ID                  ID        `json:"eventId"`
	EventType           string    `json:"eventType"`
	RequestID           RequestID `json:"requestId"`
}

// NewMessageEvent defines model for NewMessageEvent.
type NewMessageEvent struct {
	ClientID  ClientID  `json:"authorId"`
	Body      string    `json:"body"`
	ChatID    ChatID    `json:"chatId"`
	CreatedAt time.Time `json:"createdAt"`
	ID        ID        `json:"eventId"`
	EventType string    `json:"eventType"`
	MessageID MessageID `json:"messageId"`
	RequestID RequestID `json:"requestId"`
}

// RequestID defines model for RequestID.
type RequestID = types.RequestID

// AsNewChatEvent returns the union data inside the Event as a NewChatEvent
func (t Event) AsNewChatEvent() (NewChatEvent, error) {
	var body NewChatEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewChatEvent overwrites any union data inside the Event as the provided NewChatEvent
func (t *Event) FromNewChatEvent(v NewChatEvent) error {
	v.EventType = "NewChatEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewChatEvent performs a merge with any union data inside the Event, using the provided NewChatEvent
func (t *Event) MergeNewChatEvent(v NewChatEvent) error {
	v.EventType = "NewChatEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsChatClosedEvent returns the union data inside the Event as a ChatClosedEvent
func (t Event) AsChatClosedEvent() (ChatClosedEvent, error) {
	var body ChatClosedEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromChatClosedEvent overwrites any union data inside the Event as the provided ChatClosedEvent
func (t *Event) FromChatClosedEvent(v ChatClosedEvent) error {
	v.EventType = "ChatClosedEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeChatClosedEvent performs a merge with any union data inside the Event, using the provided ChatClosedEvent
func (t *Event) MergeChatClosedEvent(v ChatClosedEvent) error {
	v.EventType = "ChatClosedEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNewMessageEvent returns the union data inside the Event as a NewMessageEvent
func (t Event) AsNewMessageEvent() (NewMessageEvent, error) {
	var body NewMessageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNewMessageEvent overwrites any union data inside the Event as the provided NewMessageEvent
func (t *Event) FromNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNewMessageEvent performs a merge with any union data inside the Event, using the provided NewMessageEvent
func (t *Event) MergeNewMessageEvent(v NewMessageEvent) error {
	v.EventType = "NewMessageEvent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"eventType"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "ChatClosedEvent":
		return t.AsChatClosedEvent()
	case "NewChatEvent":
		return t.AsNewChatEvent()
	case "NewMessageEvent":
		return t.AsNewMessageEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWTW/bOBD9K8LsAnuhLSd7CXRrk6AIiiRFk54CH2hpLDGRhiw5shsE/u8FKdmyYrWO",
	"AafoyQI5w/fmzZdfINWV0YTEDpIXcGmBlQyf54Xk81I7zC4XSOyPjNUGLSsMBqmke/mE19riF6tnJVbh",
	"mJ8NQgIzrUuUBCsBaSH5KvN3/1qcQwL/xB1q3ELGHu/qwtujx9vvEGhtedwH4A0Bx1ZR7m8tfq/RveHF",
	"r63hBaxaN2Uxg+RhHULHbRtzG0EMyjJdCWjjS15grm0lGRKoa+U9+oQF/BjlekSy8oetV3vYWvofN969",
	"GqnKaNukSnIBCeSKi3o2TnUVG7SuUDTKJClVxqToUY58XKOZpKdYEaMlWcbh8SDAeakahQ/lvPYbYv3N",
	"oX1X1ptqzZRLraoUSdZ2q3yfbxqaXQJXAjTh7RySh98XyA0uveoNxErsL+jtBtpnf4PLa3RO5tjaT9fR",
	"HJ6CX4i/fu2d1V93IlJd+e7pySZ2JouA16FPxW4XtwaHa9E5DkkyeHtkUXrx/7k5mjZ9uN9j3a9/5+wd",
	"HrmbibyJ8m1j+HWp7aRD1lxoe5hqM509D4Z/cMosSsbsA/eKPJOMI1YVwkBfHDtjVdsQe1/sOuc4ed4I",
	"3+q5rYbYt4E71ttcfMI7wAPnRuc4NDcGb486N7w+iuY6ZElx6bE/SnqK7mrjUSJfNtG1JJmjjUJ+HQhY",
	"oHVKEySwOAmbzSBJoyCB/8cn4wmIQC2Ueuy4nvmPHJuNiX5jGm7crziqHbporm2UI6GVrCiPgupuHN1y",
	"gXapHEaKo0yjo/94DAHPW2rytQCfkO88iM+KM5pc02Snk0kYfZq4bUJpTKnS4Bg/Ok9g/W/0TZUNQa5+",
	"ALefg4orAQ6tlyXs977NBS6w1KZC4qixAgG1LSGBpUviuNSpLAvtODmbnE3ipQtrvP/G5enla99gOF39",
	"DAAA///MMsHBXwsAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
