// Code generated by options-gen. DO NOT EDIT.
package closechat

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	problemsRepo problemsRepository,
	messagesRepo messagesRepository,
	chatsRepo chatsRepository,
	outbox outboxService,
	transactor transactor,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.problemsRepo = problemsRepo
	o.messagesRepo = messagesRepo
	o.chatsRepo = chatsRepo
	o.outbox = outbox
	o.transactor = transactor

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("problemsRepo", _validate_Options_problemsRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("messagesRepo", _validate_Options_messagesRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("chatsRepo", _validate_Options_chatsRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("outbox", _validate_Options_outbox(o)))
	errs.Add(errors461e464ebed9.NewValidationError("transactor", _validate_Options_transactor(o)))
	return errs.AsError()
}

func _validate_Options_problemsRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.problemsRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `problemsRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_messagesRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.messagesRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `messagesRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_chatsRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.chatsRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `chatsRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_outbox(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.outbox, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `outbox` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_transactor(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.transactor, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `transactor` did not pass the test: %w", err)
	}
	return nil
}
